<template>
    <Layout class="">

    <div class="bg-white shadow-lg rounded-lg">
      <p class="p-6 mb-6">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Est iusto quidem, nihil nobis provident consequuntur eius repellat quos hic non in, tempora vero sint! Iste officiis adipisci quidem, exercitationem blanditiis, alias saepe voluptatem animi tempore perferendis nam, fugit nesciunt quod est deserunt optio magnam consequuntur repellat minima numquam ipsam dicta placeat. Eligendi temporibus rerum minima nisi distinctio, aut recusandae culpa, maiores odit molestiae quidem nam ipsam doloremque pariatur obcaecati qui, nostrum nesciunt? Cumque sit tempora eius dolorum inventore maiores beatae porro provident tenetur, aspernatur voluptatibus, veritatis blanditiis quas placeat quaerat vitae amet! Voluptates error voluptatum quos rerum doloribus? Ab quae alias necessitatibus ad, maxime sit a. Delectus perferendis, magni libero tempore explicabo doloribus voluptate vitae quo est blanditiis quos vel minima fugiat possimus optio molestiae, nisi animi autem facere commodi dolor sit aut. Quibusdam iste facilis eveniet aliquam, dolorem excepturi ad expedita omnis debitis! Doloribus repellendus reprehenderit excepturi corporis. Repellendus nesciunt earum veritatis quod accusamus vero officia deserunt vel facere assumenda, excepturi aspernatur odit ducimus facilis, alias fugiat nam vitae et iste voluptatem illum doloribus? Dolores nobis culpa minus similique voluptas, dolore eaque natus molestias soluta quidem, asperiores fugit dolor ad iure explicabo error! Provident sunt debitis voluptates facilis tempora perferendis nostrum, tempore blanditiis voluptatum ex, voluptatem recusandae quam similique cupiditate illo, laboriosam dolorum! Culpa necessitatibus cum soluta similique quae. Illo ipsa deserunt fuga harum voluptas? Corrupti iste deleniti sint incidunt. Perspiciatis voluptatem iste reprehenderit, nostrum perferendis delectus dignissimos illo, aliquam, quod ea rem minus velit vero eveniet sed voluptas. Deserunt, similique consequatur fugit cumque qui fugiat! Necessitatibus dicta voluptates repellendus, ipsum impedit, ut, fugiat facilis explicabo repellat consequuntur consectetur. Distinctio alias exercitationem odit at officiis ea soluta sit aliquid, id perspiciatis facere modi. Molestiae neque odit suscipit corrupti, eum, eaque nesciunt reprehenderit ut corporis excepturi inventore tempore maxime enim?
      </p>
    </div>
    <div class="bg-white shadow-lg grid grid-cols-2  mb-6 rounded-lg">
      <p class="p-8 mb-0 border-blue-900 bg-blue-500">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui molestias at, amet dolor illo magni. Earum, assumenda possimus. Perferendis accusamus mollitia deleniti quia ipsum reprehenderit voluptas impedit iusto architecto? Magnam eaque nemo, esse tempore quis eum doloribus assumenda quos nulla reprehenderit ab obcaecati nostrum perspiciatis aliquid, at accusantium, enim ratione? Non, aliquam possimus enim impedit neque, consequatur modi sed, recusandae commodi doloremque maxime. Iusto illum ex voluptas magni quos eveniet earum fugiat, accusamus mollitia nihil magnam harum, dolorum doloribus corporis similique perspiciatis est enim facilis. Voluptas, ipsa nobis voluptatibus sint consectetur eius perspiciatis quia quas alias expedita amet harum quam.
      </p>
      <p class="p-8 mb-0 bg-orange-400">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ducimus ullam sed perferendis illum ipsa a incidunt enim necessitatibus exercitationem, maiores labore rerum eius deserunt reprehenderit aut doloremque quo asperiores fugiat consequatur quidem sunt. Ipsam aut exercitationem eum minima possimus neque quam accusantium tempore architecto dignissimos ea, doloribus repellat ducimus incidunt sapiente, dolorum nobis quas sunt libero. Aspernatur suscipit doloremque, perspiciatis earum nulla amet cumque laboriosam, odit laborum eos delectus quos dolorem non? Suscipit possimus voluptatum ad debitis nihil assumenda doloribus incidunt perspiciatis! Corporis, exercitationem fuga animi nemo modi magni voluptates neque cum inventore, quaerat consequuntur dolore recusandae sint quia!
      </p>
      <p class="p-8 mb-0 bg-green-500">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta esse ut atque non vero dolor natus inventore harum cumque consequatur corrupti quasi explicabo molestias eius voluptatibus, asperiores modi in consequuntur architecto deserunt? Ducimus eos quidem totam cupiditate nemo deserunt, velit facilis similique placeat amet voluptates sed dolorum, quod suscipit! Blanditiis pariatur voluptas eligendi magnam quis omnis earum optio excepturi, dolor culpa dolorem, eveniet ex labore suscipit dolorum. Laudantium minus consectetur nisi commodi voluptates maiores alias, pariatur repellat qui hic magni quia. Repellat inventore consequuntur nisi asperiores, officiis, fugit necessitatibus expedita voluptatum commodi qui impedit facilis ipsa cum, eveniet tenetur est?
      </p>
      <p class="p-8 mb-0 bg-teal-400">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Numquam sit ea tempore, adipisci eum, veniam reiciendis amet illo dolore inventore iusto quisquam ratione exercitationem nisi quam vitae ex dolorem corrupti. Amet facilis deleniti hic possimus ratione dignissimos, dolores unde officia odit quibusdam consequatur temporibus? Veritatis earum ullam velit blanditiis eaque optio sequi, tempore molestias? Cupiditate perferendis aliquam quam laboriosam corporis, saepe eveniet at sunt ullam dicta unde aut expedita vel illum sit magni ducimus impedit placeat, mollitia omnis eos aperiam. Dignissimos, dolores? Eum, ad repellendus. Adipisci, minima obcaecati sed modi dicta illum deserunt cum minus quia debitis explicabo nulla numquam?
      </p>
    </div>
    <div class="bg-white shadow-lg rounded-lg">
      <p class="p-6 mb-6">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto voluptatibus soluta odio nostrum corporis voluptatem esse reprehenderit labore, illum, reiciendis ex delectus possimus porro eligendi non assumenda dolorum dolores aut molestias aspernatur et impedit. Eligendi tenetur sint qui quasi facilis facere non exercitationem inventore, corporis magni possimus rem soluta illo odit beatae fugit libero explicabo aperiam autem, eos, eaque voluptatum? Commodi nobis laboriosam odit culpa officia eaque quaerat eum exercitationem rerum fugit voluptates, optio iure quisquam dignissimos repudiandae cum inventore porro nam, quo voluptate illo, iste tempore. Delectus, quos minima nobis minus eaque sint a! Ullam reiciendis sequi possimus culpa!
      </p>
    </div>
    <div class="bg-white shadow-lg rounded-lg">
      <p class="p-6 mb-6">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Est iusto quidem, nihil nobis provident consequuntur eius repellat quos hic non in, tempora vero sint! Iste officiis adipisci quidem, exercitationem blanditiis, alias saepe voluptatem animi tempore perferendis nam, fugit nesciunt quod est deserunt optio magnam consequuntur repellat minima numquam ipsam dicta placeat. Eligendi temporibus rerum minima nisi distinctio, aut recusandae culpa, maiores odit molestiae quidem nam ipsam doloremque pariatur obcaecati qui, nostrum nesciunt? Cumque sit tempora eius dolorum inventore maiores beatae porro provident tenetur, aspernatur voluptatibus, veritatis blanditiis quas placeat quaerat vitae amet! Voluptates error voluptatum quos rerum doloribus? Ab quae alias necessitatibus ad, maxime sit a. Delectus perferendis, magni libero tempore explicabo doloribus voluptate vitae quo est blanditiis quos vel minima fugiat possimus optio molestiae, nisi animi autem facere commodi dolor sit aut. Quibusdam iste facilis eveniet aliquam, dolorem excepturi ad expedita omnis debitis! Doloribus repellendus reprehenderit excepturi corporis. Repellendus nesciunt earum veritatis quod accusamus vero officia deserunt vel facere assumenda, excepturi aspernatur odit ducimus facilis, alias fugiat nam vitae et iste voluptatem illum doloribus? Dolores nobis culpa minus similique voluptas, dolore eaque natus molestias soluta quidem, asperiores fugit dolor ad iure explicabo error! Provident sunt debitis voluptates facilis tempora perferendis nostrum, tempore blanditiis voluptatum ex, voluptatem recusandae quam similique cupiditate illo, laboriosam dolorum! Culpa necessitatibus cum soluta similique quae. Illo ipsa deserunt fuga harum voluptas? Corrupti iste deleniti sint incidunt. Perspiciatis voluptatem iste reprehenderit, nostrum perferendis delectus dignissimos illo, aliquam, quod ea rem minus velit vero eveniet sed voluptas. Deserunt, similique consequatur fugit cumque qui fugiat! Necessitatibus dicta voluptates repellendus, ipsum impedit, ut, fugiat facilis explicabo repellat consequuntur consectetur. Distinctio alias exercitationem odit at officiis ea soluta sit aliquid, id perspiciatis facere modi. Molestiae neque odit suscipit corrupti, eum, eaque nesciunt reprehenderit ut corporis excepturi inventore tempore maxime enim?
      </p>
    </div>
    <div class="bg-white shadow-lg grid grid-cols-2  mb-6 rounded-lg">
      <p class="p-8 mb-0 border-blue-900 bg-blue-500">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui molestias at, amet dolor illo magni. Earum, assumenda possimus. Perferendis accusamus mollitia deleniti quia ipsum reprehenderit voluptas impedit iusto architecto? Magnam eaque nemo, esse tempore quis eum doloribus assumenda quos nulla reprehenderit ab obcaecati nostrum perspiciatis aliquid, at accusantium, enim ratione? Non, aliquam possimus enim impedit neque, consequatur modi sed, recusandae commodi doloremque maxime. Iusto illum ex voluptas magni quos eveniet earum fugiat, accusamus mollitia nihil magnam harum, dolorum doloribus corporis similique perspiciatis est enim facilis. Voluptas, ipsa nobis voluptatibus sint consectetur eius perspiciatis quia quas alias expedita amet harum quam.
      </p>
      <p class="p-8 mb-0 bg-orange-400">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde ducimus ullam sed perferendis illum ipsa a incidunt enim necessitatibus exercitationem, maiores labore rerum eius deserunt reprehenderit aut doloremque quo asperiores fugiat consequatur quidem sunt. Ipsam aut exercitationem eum minima possimus neque quam accusantium tempore architecto dignissimos ea, doloribus repellat ducimus incidunt sapiente, dolorum nobis quas sunt libero. Aspernatur suscipit doloremque, perspiciatis earum nulla amet cumque laboriosam, odit laborum eos delectus quos dolorem non? Suscipit possimus voluptatum ad debitis nihil assumenda doloribus incidunt perspiciatis! Corporis, exercitationem fuga animi nemo modi magni voluptates neque cum inventore, quaerat consequuntur dolore recusandae sint quia!
      </p>
    </div>
    

    </Layout>
</template>

<script>
export default {
  metaInfo: {
    title: 'RCCG'
  }
}
</script>